### ISSUE TITLE
HAPP

### ISSUE THREAD

**Issue by apabari** [nightscout/NSClient-Android#4]
How would I install NSClient on my Android Device?

I am using HAPP and xDrip successfully; the only issue is that treatment information is not being uploaded to NightScout.  Do I need to 'install' / configure NS Client somehow?

**Comment by tim2000s** [comment]
I went through the same issue. Make sure you are running the current
development branch of Nightscout, and the latest version of NSClient. Doing
that fixed it for me.

**Comment by apabari** [comment]
Thanks.  I have the latest version of the Nightscout website; how do I
determine if I have the latest version of NSClient?

**Comment by MilosKozak** [comment]
https://github.com/nightscout/NSClient-Android/releases
